name: Nix Related Actions

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Nix Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check

  build:
    name: Nix build the ThreadX Demo
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build .?submodules=1 --print-build-logs
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: result/
